### PR TITLE
Missing i18n in profile-activity

### LINKED ISSUE #151: Missing i18n in profile-activity
When a user registered, a `_construct ` event is created and the representational text on Profile Activity is "{{USERNAME}} joined". This has to be added to i18n.

### PR DESCRIPTION
**Pull request by ChaituVR**
Closes #151

### CODE REVIEW

**Comment by ChaituVR** [comment]
> Please check the code before deleting things.
> Here it states `noActivityText || 'There is no activity.'` which means if `noActivityText` doesn't exist, show the `'There is no activity.'` text. You should be changing the text in English. The first one comes from the attribute.
> 
> `this.noActivityText = opts.noActivityText;`
> 
> Read the code first. Don't destroy things.

@ozanilbey The i18n code handles this.. if the user passes noActivityText from the opts it will take it.. else it will take from the i18N 

It will not break anything and works similar to previous `||` statement

**Comment by ozanilbey** [comment]
> > Please check the code before deleting things.
> > Here it states `noActivityText || 'There is no activity.'` which means if `noActivityText` doesn't exist, show the `'There is no activity.'` text. You should be changing the text in English. The first one comes from the attribute.
> > `this.noActivityText = opts.noActivityText;`
> > Read the code first. Don't destroy things.
> 
> @ozanilbey The i18n code handles this.. if the user passes noActivityText from the opts it will take it.. else it will take from the i18N
> 
> It will not break anything and works similar to previous `||` statement

Please read the code one more time. You are not getting anything from **opts** now because you completely destroyed it.

**Comment by ChaituVR** [comment]
It is handled in later part of the code 

        i18n = {...i18n,...JSON.parse(JSON.stringify(opts))}

which takes the `i18n.noActivityText` string as default and if the user gives opts it will overwrite it.. so we dont need a || as we already have a default value from i18n

**Comment by ChaituVR** [comment]
It won't conflict, it will overwrite the i18n, Tested it, working fine as expected
image


As discussed with @esokullu 
we give priority to user defined opts For example if user provides 
`<profile-activity no-activity-text="Activity not Existing"/>`

it will overwrite the default i18n.noActivityText value of ''There is no activity."

It will display `Activity not Existing` this is what expected behaviour (which is what we have in current code)

**Comment by ozanilbey** [comment]
Users can change a text value only if we let them change through opts. If we don't want something to change, let's say items on the profile-header menu (Activity, Followers, Followings, Groups), they shouldn't be changing it. They can use`<profile-header followers-text="000 Followers" />` to make their follower count thousand times as much.

**Comment by ChaituVR** [comment]
No, we've handled these type of things too by having a wild card `%s` so that only text part is coming from either i18n or user opts

In this particular case we are only having the text part 
```
"followersText":"Followers",
"followingText":"Following",
```
so user can only pass the text part from opts
and if `"000 Followers is passed"` it will be `1 000 Followers` which is true but as far as i know this will be handled by website admins right?? user can any way change it from inspecting it irrespective of i18n or our code

maybe @esokullu can help whether to keep this or feature or remove?

**Comment by ozanilbey** [comment]
Overwriting **i18n** with **opts** is wrong on so many levels. They can even pass harmful functions to the code through attributes. Do not put apples and oranges together, **opts** is not a language pack. If we let anyone change text values, we can do it with a control, not without controlling.

**Comment by ChaituVR** [comment]
> i18n = {...i18n,...JSON.parse(JSON.stringify(opts))}

For functions, that is where `JSON.parse(JSON.stringify(opts))` is super helpful it will clean the functions, no way to pass through this, only strings or numbers in our case

image

**Pull request merged**
